"use client";
import { Inter } from "next/font/google";
import styles from "./page.module.css";
import React, { use } from "react";
import Head from "next/head";
// import ManualHeader from "@/components/ManualHeader";
import Header from "@/components/Header";
import LotteryEntrance from "@/components/LotteryEntrance";
import { useMoralis } from "react-moralis";

const inter = Inter({ subsets: ["latin"] });
const supportedChains = ["1337", "11155111"];
const Home: React.FC = () => {
  const { isWeb3Enabled, chainId } = useMoralis();
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="stylesheet" href="/dist/output.css" />
      </Head>
      <Header />
      {isWeb3Enabled ? (
        <div>
          {supportedChains.includes(parseInt(chainId!).toString()) ? (
            <div className="flex flex-row">
              <LotteryEntrance />
            </div>
          ) : (
            <div>{`Please switch to a supported chainId. The supported Chain Ids are: ${supportedChains}`}</div>
          )}
        </div>
      ) : (
        <div>Please connect to a Wallet</div>
      )}
    </div>
  );
};

export default Home;
